language: java
jdk:
- oraclejdk8
services:
- mysql
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- mysql -u root -e 'CREATE DATABASE users;'
- mysql -u root users < database/MySQL/users.sql
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start