CREATE TABLE USER(
	ID BIGINT NOT NULL PRIMARY KEY,
	ADDRESS VARCHAR(255),
	EMAIL VARCHAR(255),
	NATIONALITY VARCHAR(255),
	DATEOFBIRTH TIMESTAMP,
	FIRSTNAME VARCHAR(255),
	IDENTIFICATION VARCHAR(255),
	LASTNAME VARCHAR(255),
	PASSWORD VARCHAR(255)
);

CREATE TABLE SEQUENCE(
	SEQ_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
	SEQ_COUNT NUMERIC(38)
);